CREATE TABLE fs_fiadb.plot
(
cn                             VARCHAR(34) NOT NULL,
srv_cn                         VARCHAR(34) NOT NULL,
cty_cn                         VARCHAR(34) NOT NULL,
prev_plt_cn                    VARCHAR(34),
invyr                          INTEGER NOT NULL,
statecd                        INTEGER NOT NULL,
unitcd                         INTEGER NOT NULL,
countycd                       INTEGER NOT NULL,
plot                           INTEGER NOT NULL,
plot_status_cd                 INTEGER,
plot_nonsample_reasn_cd        INTEGER,
measyear                       INTEGER,
measmon                        INTEGER,
measday                        INTEGER,
remper                         DECIMAL(3,1),
kindcd                         INTEGER NOT NULL,
designcd                       INTEGER,
rddistcd                       INTEGER,
watercd                        INTEGER,
lat                            DECIMAL(8,6),
lon                            DECIMAL(9,6),
elev                           INTEGER,
grow_typ_cd                    INTEGER,
mort_typ_cd                    INTEGER,
p2panel                        INTEGER,
p3panel                        INTEGER,
ecosubcd                       VARCHAR(7),
congcd                         INTEGER,
manual                         DECIMAL(3,1) NOT NULL,
kindcd_nc                      INTEGER,
qa_status                      INTEGER,
created_by                     VARCHAR(30),
created_date                   TIMESTAMP(0),
created_in_instance            VARCHAR(6),
modified_by                    VARCHAR(30),
modified_date                  TIMESTAMP(0),
modified_in_instance           VARCHAR(6),
microplot_loc                  VARCHAR(12),
declination                    DECIMAL(4,1),
emap_hex                       INTEGER,
samp_method_cd                 INTEGER,
subp_examine_cd                INTEGER NOT NULL,
macro_breakpoint_dia           INTEGER,
intensity                      VARCHAR(3),
cycle                          INTEGER,
subcycle                       INTEGER,
eco_unit_pnw                   VARCHAR(10),
topo_position_pnw              VARCHAR(2),
nf_sampling_status_cd          INTEGER,
nf_plot_status_cd              INTEGER,
nf_plot_nonsample_reasn_cd     INTEGER,
p2veg_sampling_status_cd       INTEGER,
p2veg_sampling_level_detail_cd INTEGER,
invasive_sampling_status_cd    INTEGER,
invasive_specimen_rule_cd      INTEGER,
designcd_p2a                   INTEGER,
manual_db                      DECIMAL(3,1),
subpanel                       INTEGER,
condchngcd_rmrs                INTEGER,
futforcd_rmrs                  INTEGER,
manual_ncrs                    DECIMAL(4,2),
manual_ners                    DECIMAL(4,2),
manual_rmrs                    DECIMAL(4,2),
pac_island_pnwrs               VARCHAR(20),
plot_season_ners               INTEGER,
precipitation                  DOUBLE PRECISION,
prev_microplot_loc_rmrs        VARCHAR(12),
prev_plot_status_cd_rmrs       INTEGER,
reusecd1                       INTEGER,
reusecd2                       INTEGER,
reusecd3                       INTEGER,
grnd_lyr_sampling_status_cd    INTEGER,
grnd_lyr_sampling_method_cd    INTEGER
);
create index PLT_SRV_FK_I on FS_FIADB.PLOT (SRV_CN);
create index PLT_CTY_FK_I on FS_FIADB.PLOT (CTY_CN);
alter table FS_FIADB.PLOT add constraint PLT_PK primary key (CN);
alter table FS_FIADB.PLOT add constraint PLT_UK unique (STATECD, INVYR, UNITCD, COUNTYCD, PLOT);
alter table FS_FIADB.PLOT add constraint PLT_CTY_FK foreign key (CTY_CN) references FS_FIADB.COUNTY (CN);
alter table FS_FIADB.PLOT add constraint PLT_SRV_FK foreign key (SRV_CN) references FS_FIADB.SURVEY (CN);