CREATE TABLE fs_fiadb.cond
(
cn                            VARCHAR(34) NOT NULL,
plt_cn                        VARCHAR(34) NOT NULL,
invyr                         INTEGER NOT NULL,
statecd                       INTEGER NOT NULL,
unitcd                        INTEGER NOT NULL,
countycd                      INTEGER NOT NULL,
plot                          INTEGER NOT NULL,
condid                        INTEGER NOT NULL,
cond_status_cd                INTEGER NOT NULL,
cond_nonsample_reasn_cd       INTEGER,
reservcd                      INTEGER,
owncd                         INTEGER,
owngrpcd                      INTEGER,
adforcd                       INTEGER,
fortypcd                      INTEGER,
fldtypcd                      INTEGER,
mapden                        INTEGER,
stdage                        INTEGER,
stdszcd                       INTEGER,
fldszcd                       INTEGER,
siteclcd                      INTEGER,
sicond                        INTEGER,
sibase                        INTEGER,
sisp                          INTEGER,
stdorgcd                      INTEGER,
stdorgsp                      DOUBLE PRECISION,
prop_basis                    VARCHAR(12),
condprop_unadj                DOUBLE PRECISION,
micrprop_unadj                DOUBLE PRECISION,
subpprop_unadj                DOUBLE PRECISION,
macrprop_unadj                DOUBLE PRECISION,
slope                         INTEGER,
aspect                        INTEGER,
physclcd                      INTEGER,
gsstkcd                       INTEGER,
alstkcd                       INTEGER,
dstrbcd1                      INTEGER,
dstrbyr1                      INTEGER,
dstrbcd2                      INTEGER,
dstrbyr2                      INTEGER,
dstrbcd3                      INTEGER,
dstrbyr3                      INTEGER,
trtcd1                        INTEGER,
trtyr1                        INTEGER,
trtcd2                        INTEGER,
trtyr2                        INTEGER,
trtcd3                        INTEGER,
trtyr3                        INTEGER,
presnfcd                      INTEGER,
balive                        DECIMAL(9,4),
fldage                        INTEGER,
alstk                         DECIMAL(7,4),
gsstk                         DECIMAL(7,4),
fortypcdcalc                  INTEGER,
habtypcd1                     VARCHAR(10),
habtypcd1_pub_cd              VARCHAR(10),
habtypcd1_descr_pub_cd        VARCHAR(10),
habtypcd2                     VARCHAR(10),
habtypcd2_pub_cd              VARCHAR(10),
habtypcd2_descr_pub_cd        VARCHAR(10),
mixedconfcd                   VARCHAR(1),
vol_loc_grp                   VARCHAR(200),
siteclcdest                   INTEGER,
sitetree_tree                 INTEGER,
sitecl_method                 INTEGER,
carbon_down_dead              DECIMAL(13,6),
carbon_litter                 DECIMAL(13,6),
carbon_soil_org               DECIMAL(13,6),
carbon_understory_ag          DECIMAL(13,6),
carbon_understory_bg          DECIMAL(13,6),
created_date                  TIMESTAMP(0),
modified_date                 TIMESTAMP(0),
cycle                         INTEGER,
subcycle                      INTEGER,
soil_rooting_depth_pnw        VARCHAR(1),
ground_land_class_pnw         VARCHAR(3),
plant_stockability_factor_pnw DOUBLE PRECISION,
stnd_cond_cd_pnwrs            INTEGER,
stnd_struc_cd_pnwrs           INTEGER,
stump_cd_pnwrs                VARCHAR(1),
fire_srs                      INTEGER,
grazing_srs                   INTEGER,
harvest_type1_srs             INTEGER,
harvest_type2_srs             INTEGER,
harvest_type3_srs             INTEGER,
land_use_srs                  INTEGER,
operability_srs               INTEGER,
stand_structure_srs           INTEGER,
nf_cond_status_cd             INTEGER,
nf_cond_nonsample_reasn_cd    INTEGER,
canopy_cvr_sample_method_cd   INTEGER,
live_canopy_cvr_pct           INTEGER,
live_missing_canopy_cvr_pct   INTEGER,
nbr_live_stems                INTEGER,
ownsubcd                      INTEGER,
industrialcd_fiadb            INTEGER,
reservcd_5                    INTEGER,
admin_withdrawn_cd            INTEGER,
chaining_cd                   INTEGER,
land_cover_class_cd_ret       INTEGER,
afforestation_cd              INTEGER,
prev_afforestation_cd         INTEGER,
dwm_fuelbed_typcd             VARCHAR(3),
nvcs_primary_class            VARCHAR(8),
nvcs_level_1_cd               VARCHAR(25),
nvcs_level_2_cd               VARCHAR(25),
nvcs_level_3_cd               VARCHAR(25),
nvcs_level_4_cd               VARCHAR(25),
nvcs_level_5_cd               VARCHAR(25),
nvcs_level_6_cd               VARCHAR(25),
nvcs_level_7_cd               VARCHAR(25),
nvcs_level_8_cd               VARCHAR(25),
age_basis_cd_pnwrs            INTEGER,
cond_status_chng_cd_rmrs      INTEGER,
crcovpct_rmrs                 INTEGER,
dominant_species1_pnwrs       INTEGER,
dominant_species2_pnwrs       INTEGER,
dominant_species3_pnwrs       INTEGER,
dstrbcd1_p2a                  INTEGER,
dstrbcd2_p2a                  INTEGER,
dstrbcd3_p2a                  INTEGER,
dstrbyr1_p2a                  INTEGER,
dstrbyr2_p2a                  INTEGER,
dstrbyr3_p2a                  INTEGER,
fldtypcd_30                   INTEGER,
forest_community_pnwrs        INTEGER,
land_usecd_rmrs               INTEGER,
maicf                         DECIMAL(5,2),
pctbare_rmrs                  INTEGER,
qmd_rmrs                      DECIMAL(5,1),
rangetypcd_rmrs               INTEGER,
sdimax_rmrs                   INTEGER,
sdipct_rmrs                   DECIMAL(4,1),
sdi_rmrs                      DECIMAL(8,4),
stand_structure_me_ners       INTEGER,
trees_present_ncrs            INTEGER,
trees_present_ners            INTEGER,
trtcd1_p2a                    INTEGER,
trtcd2_p2a                    INTEGER,
trtcd3_p2a                    INTEGER,
trtopcd                       INTEGER,
trtyr1_p2a                    INTEGER,
trtyr2_p2a                    INTEGER,
trtyr3_p2a                    INTEGER,
land_cover_class_cd           INTEGER,
sieqn_ref_cd                  VARCHAR(10),
sicond_fvs                    INTEGER,
sibase_fvs                    INTEGER,
sisp_fvs                      INTEGER,
sieqn_ref_cd_fvs              VARCHAR(10),
mquadprop_unadj               DECIMAL(11,10),
soilprop_unadj                DECIMAL(11,10),
forest_cond_status_change_cd  INTEGER
);
create index CND_NAT_I on FS_FIADB.COND (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, CONDID);
create index CND_PLT_FK_I on FS_FIADB.COND (PLT_CN);
alter table FS_FIADB.COND add constraint CND_PK primary key (CN);
alter table FS_FIADB.COND add constraint CND_UK unique (PLT_CN, CONDID);
alter table FS_FIADB.COND add constraint CND_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);