create table fs_fiadb.REF_FVS_VAR_NAME
(
 CN                   VARCHAR(34) not null,
 FVS_VARIANT          VARCHAR(5) not null,
 FVS_VAR_NAME         VARCHAR(100),
 MANUAL_START         VARCHAR(30),
 MANUAL_END           VARCHAR(30),
 ALLOWED_IN_FIELD     VARCHAR(30),
 CREATED_BY           VARCHAR(30),
 CREATED_DATE         TIMESTAMP(0),
 CREATED_IN_INSTANCE  VARCHAR(30),
 MODIFIED_BY          VARCHAR(30),
 MODIFIED_DATE        TIMESTAMP(0),
 MODIFIED_IN_INSTANCE VARCHAR(30)
);