-- Create table
create table FS_FIADB.PLOTSNAP
(
  cn                      VARCHAR(34) not null,
  srv_cn                  VARCHAR(34) not null,
  cty_cn                  VARCHAR(34),
  prev_plt_cn             VARCHAR(34),
  invyr                   SMALLINT not null,
  statecd                 SMALLINT not null,
  unitcd                  SMALLINT not null,
  countycd                SMALLINT not null,
  plot                    INT not null,
  plot_status_cd          SMALLINT,
  plot_nonsample_reasn_cd SMALLINT,
  measyear                SMALLINT,
  measmon                 SMALLINT,
  measday                 SMALLINT,
  remper                  DECIMAL(3,1),
  kindcd                  SMALLINT not null,
  designcd                SMALLINT,
  rddistcd                SMALLINT,
  watercd                 SMALLINT,
  lat                     DECIMAL(8,6),
  lon                     DECIMAL(9,6),
  elev                    INT,
  grow_typ_cd             SMALLINT,
  mort_typ_cd             SMALLINT,
  p2panel                 SMALLINT,
  p3panel                 SMALLINT,
  ecosubcd                VARCHAR(7),
  congcd                  SMALLINT,
  manual                  DECIMAL(3,1) not null,
  manual_db               DECIMAL(3,1),
  subpanel                SMALLINT,
  kindcd_nc               SMALLINT,
  qa_status               SMALLINT,
  created_by              VARCHAR(30),
  created_date            TIMESTAMP(0),
  created_in_instance     VARCHAR(6),
  modified_by             VARCHAR(30),
  modified_date           TIMESTAMP(0),
  modified_in_instance    VARCHAR(6),
  microplot_loc           VARCHAR(12),
  declination             DECIMAL(4,1),
  emap_hex                INT,
  samp_method_cd          SMALLINT,
  subp_examine_cd         SMALLINT not null,
  macro_breakpoint_dia    SMALLINT,
  intensity               VARCHAR(3),
  cycle                   SMALLINT,
  subcycle                SMALLINT,
  eco_unit_pnw            VARCHAR(10),
  topo_position_pnw       VARCHAR(2),
  eval_grp_cn             VARCHAR(34) not null,
  eval_grp                INT not null,
  expall                  DOUBLE PRECISION,
  expcurr                 DOUBLE PRECISION,
  expvol                  DOUBLE PRECISION,
  expgrow                 DOUBLE PRECISION,
  expmort                 DOUBLE PRECISION,
  expremv                 DOUBLE PRECISION,
  adj_expall              DOUBLE PRECISION,
  adj_expcurr             DOUBLE PRECISION,
  adj_expvol_macr         DOUBLE PRECISION,
  adj_expvol_subp         DOUBLE PRECISION,
  adj_expvol_micr         DOUBLE PRECISION,
  adj_expgrow_macr        DOUBLE PRECISION,
  adj_expgrow_subp        DOUBLE PRECISION,
  adj_expgrow_micr        DOUBLE PRECISION,
  adj_expmort_macr        DOUBLE PRECISION,
  adj_expmort_subp        DOUBLE PRECISION,
  adj_expmort_micr        DOUBLE PRECISION,
  adj_expremv_macr        DOUBLE PRECISION,
  adj_expremv_subp        DOUBLE PRECISION,
  adj_expremv_micr        DOUBLE PRECISION
);
alter table FS_FIADB.PLOTSNAP
  add constraint PLTSNAP_PK primary key (CN,eval_grp);
