create table fs_fiadb.REF_INTL_TO_DOYLE_FACTOR
(
 DIA_2INCH_CLASS      INTEGER,
 SOFTWOOD             VARCHAR(1),
 FACTOR               DECIMAL(8,5),
 CREATED_BY           VARCHAR(30),
 CREATED_DATE         TIMESTAMP(0),
 CREATED_IN_INSTANCE  VARCHAR(6),
 MODIFIED_BY          VARCHAR(30),
 MODIFIED_DATE        TIMESTAMP(0),
 MODIFIED_IN_INSTANCE VARCHAR(6)
);