CREATE TABLE fs_fiadb.ref_species
(
spcd                         DOUBLE PRECISION,
common_name                  VARCHAR(100) NOT NULL,
shared_common_name_ind       CHAR(1),
genus                        VARCHAR(4000),
species                      VARCHAR(4000),
variety                      VARCHAR(4000),
subspecies                   VARCHAR(4000),
scientific_name              VARCHAR(4000),
species_symbol               VARCHAR(10),
e_spgrpcd                    DOUBLE PRECISION,
w_spgrpcd                    DOUBLE PRECISION,
c_spgrpcd                    DOUBLE PRECISION,
p_spgrpcd                    DOUBLE PRECISION,
major_spgrpcd                DOUBLE PRECISION,
stocking_spgrpcd             DOUBLE PRECISION,
forest_type_spgrpcd          DOUBLE PRECISION,
jenkins_spgrpcd              DOUBLE PRECISION,
jenkins_sapling_adjustment   DOUBLE PRECISION,
sitetree                     VARCHAR(1),
sftwd_hrdwd                  VARCHAR(1),
woodland                     VARCHAR(1),
wood_spgr_greenvol_drywt     DOUBLE PRECISION,
wood_spgr_greenvol_drywt_cit DOUBLE PRECISION,
bark_spgr_greenvol_drywt     DOUBLE PRECISION,
bark_spgr_greenvol_drywt_cit DOUBLE PRECISION,
mc_pct_green_wood            DOUBLE PRECISION,
mc_pct_green_wood_cit        DOUBLE PRECISION,
mc_pct_green_bark            DOUBLE PRECISION,
mc_pct_green_bark_cit        DOUBLE PRECISION,
bark_vol_pct                 DOUBLE PRECISION,
bark_vol_pct_cit             DOUBLE PRECISION,
cwd_decay_ratio1             DOUBLE PRECISION,
cwd_decay_ratio2             DOUBLE PRECISION,
cwd_decay_ratio3             DOUBLE PRECISION,
cwd_decay_ratio4             DOUBLE PRECISION,
cwd_decay_ratio5             DOUBLE PRECISION,
dwm_carbon_ratio             DOUBLE PRECISION,
carbon_ratio_live            DOUBLE PRECISION,
drywt_to_greenwt_conversion  DOUBLE PRECISION,
created_date                 TIMESTAMP(0) NOT NULL,
modified_date                TIMESTAMP(0)
);
create index RS_SPCD_I on FS_FIADB.REF_SPECIES (SPCD);
create index RS_SPSYM_I on FS_FIADB.REF_SPECIES (SPECIES_SYMBOL);
create index RS_COMMON_NAME_I on FS_FIADB.REF_SPECIES (COMMON_NAME);