CREATE TABLE fs_fiadb.ref_nvcs_hierarchy_strct
(
hierarchy_version    VARCHAR(30) NOT NULL,
primary_class        VARCHAR(8) NOT NULL,
nvcs_level_1_label   VARCHAR(30) NOT NULL,
nvcs_level_1_cd      VARCHAR(3) NOT NULL,
nvcs_level_2_label   VARCHAR(30) NOT NULL,
nvcs_level_2_cd      VARCHAR(8) NOT NULL,
nvcs_level_3_label   VARCHAR(30) NOT NULL,
nvcs_level_3_cd      VARCHAR(10) NOT NULL,
nvcs_level_4_label   VARCHAR(30) NOT NULL,
nvcs_level_4_cd      VARCHAR(13) NOT NULL,
nvcs_level_5_label   VARCHAR(30) NOT NULL,
nvcs_level_5_cd      VARCHAR(20) NOT NULL,
nvcs_level_6_label   VARCHAR(30),
nvcs_level_6_cd      VARCHAR(20),
nvcs_level_7_label   VARCHAR(30),
nvcs_level_7_cd      VARCHAR(25),
nvcs_level_8_label   VARCHAR(30),
nvcs_level_8_cd      VARCHAR(25),
nvcs_level_1_meaning VARCHAR(100) NOT NULL,
nvcs_level_2_meaning VARCHAR(100) NOT NULL,
nvcs_level_3_meaning VARCHAR(100) NOT NULL,
nvcs_level_4_meaning VARCHAR(100) NOT NULL,
nvcs_level_5_meaning VARCHAR(100) NOT NULL,
nvcs_level_6_meaning VARCHAR(100),
nvcs_level_7_meaning VARCHAR(100),
nvcs_level_8_meaning VARCHAR(100),
nvcs_level_1_note    VARCHAR(1000),
nvcs_level_2_note    VARCHAR(1000),
nvcs_level_3_note    VARCHAR(1000),
nvcs_level_4_note    VARCHAR(1000),
nvcs_level_5_note    VARCHAR(1000),
nvcs_level_6_note    VARCHAR(1000),
nvcs_level_7_note    VARCHAR(1000),
nvcs_level_8_note    VARCHAR(1000),
citation_nbr         INTEGER,
created_date         TIMESTAMP(0) NOT NULL,
modified_date        TIMESTAMP(0)
);