CREATE TABLE fs_fiadb.ozone_species_summary
(
cn             VARCHAR(34) NOT NULL,
invyr          INTEGER NOT NULL,
statecd        INTEGER NOT NULL,
countycd       INTEGER NOT NULL,
o3plot         DOUBLE PRECISION NOT NULL,
field_id       INTEGER NOT NULL,
split_plotid   INTEGER NOT NULL,
ground_loc_cd  INTEGER NOT NULL,
measyear       INTEGER NOT NULL,
biospcd        DOUBLE PRECISION NOT NULL,
amnt_max       DOUBLE PRECISION NOT NULL,
amnt_min       DOUBLE PRECISION NOT NULL,
amnt_mean      DOUBLE PRECISION NOT NULL,
svrty_max      DOUBLE PRECISION NOT NULL,
svrty_min      DOUBLE PRECISION NOT NULL,
svrty_mean     DOUBLE PRECISION NOT NULL,
plant_inj_cnt  DOUBLE PRECISION NOT NULL,
plant_eval_cnt DOUBLE PRECISION NOT NULL,
plant_ratio    DOUBLE PRECISION NOT NULL,
biospcd_sum    DOUBLE PRECISION NOT NULL,
biospcd_index  DOUBLE PRECISION NOT NULL,
elev           INTEGER,
pltsize        DOUBLE PRECISION,
aspect         INTEGER,
terrpos        DOUBLE PRECISION,
soildpth       DOUBLE PRECISION,
soildrn        DOUBLE PRECISION,
plotwet        DOUBLE PRECISION,
pltdstrb       DOUBLE PRECISION,
created_date   TIMESTAMP(0),
modified_date  TIMESTAMP(0)
);
alter table FS_FIADB.OZONE_SPECIES_SUMMARY add constraint OSY_PK primary key (CN);
alter table FS_FIADB.OZONE_SPECIES_SUMMARY add constraint OSY_UK unique (STATECD, INVYR, COUNTYCD, O3PLOT, BIOSPCD);