create table fs_fiadb.REF_GRND_LYR
(
 CN                  VARCHAR(34) not null,
 GRND_LYR_CONFIG     VARCHAR(10),
 FUNCTIONAL_GROUP_CD VARCHAR(5),
 CARBON_PCT          DECIMAL(8,5),
 NITROGEN_PCT        DECIMAL(8,5),
 BULKDENSITY_COEFF_M DECIMAL(8,5),
 BULKDENSITY_COEFF_A DECIMAL(8,5),
 BULKDENSITY_COEFF_B DECIMAL(8,5),
 CREATED_DATE        TIMESTAMP(0),
 MODIFIED_DATE       TIMESTAMP(0)
);