CREATE TABLE fs_fiadb.dwm_coarse_woody_debris
(
cn                  VARCHAR(34) NOT NULL,
plt_cn              VARCHAR(34) NOT NULL,
invyr               INTEGER NOT NULL,
statecd             INTEGER NOT NULL,
countycd            INTEGER NOT NULL,
plot                INTEGER NOT NULL,
subp                INTEGER NOT NULL,
transect            INTEGER NOT NULL,
cwdid               DOUBLE PRECISION NOT NULL,
measyear            INTEGER,
condid              INTEGER,
slopdist            DOUBLE PRECISION,
horiz_dist          DOUBLE PRECISION,
spcd                DOUBLE PRECISION,
decaycd             INTEGER,
transdia            INTEGER,
smalldia            INTEGER,
largedia            INTEGER,
length              INTEGER,
hollowcd            VARCHAR(1),
cwdhstcd            INTEGER,
volcf               DOUBLE PRECISION,
drybio              DOUBLE PRECISION,
carbon              DOUBLE PRECISION,
cover_pct           DOUBLE PRECISION,
lpa_unadj           DOUBLE PRECISION,
lpa_plot            DOUBLE PRECISION,
lpa_cond            DOUBLE PRECISION,
lpa_unadj_rgn       DOUBLE PRECISION,
lpa_plot_rgn        DOUBLE PRECISION,
lpa_cond_rgn        DOUBLE PRECISION,
cover_pct_rgn       DOUBLE PRECISION,
charred_cd          INTEGER,
orntcd_pnwrs        VARCHAR(1),
created_date        TIMESTAMP(0),
modified_date       TIMESTAMP(0),
cwd_sample_method   VARCHAR(6),
hollow_dia          INTEGER,
horiz_dist_cd       INTEGER,
inclination         INTEGER,
large_end_dia_class INTEGER,
length_cd           INTEGER,
volcf_ac_unadj      DOUBLE PRECISION,
volcf_ac_plot       DOUBLE PRECISION,
volcf_ac_cond       DOUBLE PRECISION,
drybio_ac_unadj     DOUBLE PRECISION,
drybio_ac_plot      DOUBLE PRECISION,
drybio_ac_cond      DOUBLE PRECISION,
carbon_ac_unadj     DOUBLE PRECISION,
carbon_ac_plot      DOUBLE PRECISION,
carbon_ac_cond      DOUBLE PRECISION
);
create index DCW_NAT_I on FS_FIADB.DWM_COARSE_WOODY_DEBRIS (STATECD, INVYR, COUNTYCD, PLOT, TRANSECT, SUBP, CWDID);
alter table FS_FIADB.DWM_COARSE_WOODY_DEBRIS add constraint DCW_PK primary key (CN);
alter table FS_FIADB.DWM_COARSE_WOODY_DEBRIS add constraint DCW_UK unique (PLT_CN, TRANSECT, SUBP, CWDID);