CREATE TABLE fs_fiadb.subp_soil_sample_layer
(
cn                            VARCHAR(34) NOT NULL,
sssl_cn                       VARCHAR(34) NOT NULL,
plt_cn                        VARCHAR(34) NOT NULL,
statecd                       INTEGER NOT NULL,
countycd                      INTEGER NOT NULL,
plot                          INTEGER NOT NULL,
invyr                         INTEGER NOT NULL,
inv_vst_nbr                   INTEGER NOT NULL,
cycle                         INTEGER NOT NULL,
subcycle                      INTEGER NOT NULL,
subp                          INTEGER NOT NULL,
vstnbr                        INTEGER,
sampler_type                  VARCHAR(2),
sample_dia                    DECIMAL(7,3),
layer_type                    VARCHAR(30) NOT NULL,
soil_samp_per_ac              DECIMAL(14,6),
layer_thickness               DECIMAL(5,3),
layer_collected_cd            INTEGER,
wt_field_moist                DECIMAL(7,2),
wt_air_dry                    DECIMAL(7,2),
wt_oven_dry                   DECIMAL(7,2),
wt_rock                       DECIMAL(7,2),
water_content_pct_field_moist DECIMAL(6,2),
water_content_pct_residual    DECIMAL(6,2),
water_content_pct_total       DECIMAL(6,2),
bulk_density                  DECIMAL(10,6),
coarse_fraction_pct           DECIMAL(7,3),
bulk_density_fines            DECIMAL(10,6),
texture_cd                    INTEGER,
ph_h2o                        DECIMAL(7,3),
ph_cacl2                      DECIMAL(7,3),
ecec                          DECIMAL(7,3),
exchng_al                     DECIMAL(7,3),
exchng_ca                     DECIMAL(8,3),
exchng_cd                     DECIMAL(7,3),
exchng_cu                     DECIMAL(7,3),
exchng_fe                     DECIMAL(7,3),
exchng_k                      DECIMAL(7,3),
exchng_mg                     DECIMAL(8,3),
exchng_mn                     DECIMAL(7,3),
exchng_na                     DECIMAL(8,3),
exchng_ni                     DECIMAL(7,3),
exchng_pb                     DECIMAL(7,3),
exchng_s                      DECIMAL(8,3),
exchng_zn                     DECIMAL(7,3),
bray1_p                       DECIMAL(7,3),
olsen_p                       DECIMAL(7,3),
c_org_pct                     DECIMAL(7,3),
c_inorg_pct                   DECIMAL(7,3),
c_total_pct                   DECIMAL(7,3),
c_mg_ac                       DECIMAL(10,6),
c_min3_mg_ac                  DECIMAL(10,6),
n_total_pct                   DECIMAL(7,3),
n_mg_ac                       DECIMAL(10,6),
n_min3_mg_ac                  DECIMAL(10,6),
created_date                  TIMESTAMP(0),
modified_date                 TIMESTAMP(0)
);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LAYER add constraint SSSLYR_PK primary key (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LAYER add constraint SSSLYR_FK2 foreign key (SSSL_CN) references FS_FIADB.SUBP_SOIL_SAMPLE_LOC (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LAYER add constraint SSSLYR_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);