CREATE TABLE fs_fiadb.cond_dwm_calc
(
cn                     VARCHAR(34) NOT NULL,
statecd                INTEGER NOT NULL,
countycd               INTEGER NOT NULL,
plot                   INTEGER NOT NULL,
measyear               INTEGER NOT NULL,
invyr                  INTEGER NOT NULL,
condid                 INTEGER NOT NULL,
evalid                 INTEGER NOT NULL,
plt_cn                 VARCHAR(34) NOT NULL,
cnd_cn                 VARCHAR(34),
stratum_cn             VARCHAR(34),
phase                  VARCHAR(3),
condprop_cwd           DECIMAL(13,12),
condprop_fwd_sm        DECIMAL(13,12),
condprop_fwd_md        DECIMAL(13,12),
condprop_fwd_lg        DECIMAL(13,12),
condprop_duff          DECIMAL(13,12),
cwd_tl_cond            DECIMAL(13,10),
cwd_tl_unadj           DECIMAL(13,10),
cwd_tl_adj             DECIMAL(13,10),
cwd_lpa_cond           DOUBLE PRECISION,
cwd_lpa_unadj          DOUBLE PRECISION,
cwd_lpa_adj            DOUBLE PRECISION,
cwd_volcf_cond         DOUBLE PRECISION,
cwd_volcf_unadj        DOUBLE PRECISION,
cwd_volcf_adj          DOUBLE PRECISION,
cwd_drybio_cond        DOUBLE PRECISION,
cwd_drybio_unadj       DOUBLE PRECISION,
cwd_drybio_adj         DOUBLE PRECISION,
cwd_carbon_cond        DOUBLE PRECISION,
cwd_carbon_unadj       DOUBLE PRECISION,
cwd_carbon_adj         DOUBLE PRECISION,
fwd_sm_tl_cond         DECIMAL(13,10),
fwd_sm_tl_unadj        DECIMAL(13,10),
fwd_sm_tl_adj          DECIMAL(13,10),
fwd_sm_cnt_cond        DOUBLE PRECISION,
fwd_sm_volcf_cond      DOUBLE PRECISION,
fwd_sm_volcf_unadj     DOUBLE PRECISION,
fwd_sm_volcf_adj       DOUBLE PRECISION,
fwd_sm_drybio_cond     DOUBLE PRECISION,
fwd_sm_drybio_unadj    DOUBLE PRECISION,
fwd_sm_drybio_adj      DOUBLE PRECISION,
fwd_sm_carbon_cond     DOUBLE PRECISION,
fwd_sm_carbon_unadj    DOUBLE PRECISION,
fwd_sm_carbon_adj      DOUBLE PRECISION,
fwd_md_tl_cond         DECIMAL(13,10),
fwd_md_tl_unadj        DECIMAL(13,10),
fwd_md_tl_adj          DECIMAL(13,10),
fwd_md_cnt_cond        DOUBLE PRECISION,
fwd_md_volcf_cond      DOUBLE PRECISION,
fwd_md_volcf_unadj     DOUBLE PRECISION,
fwd_md_volcf_adj       DOUBLE PRECISION,
fwd_md_drybio_cond     DOUBLE PRECISION,
fwd_md_drybio_unadj    DOUBLE PRECISION,
fwd_md_drybio_adj      DOUBLE PRECISION,
fwd_md_carbon_cond     DOUBLE PRECISION,
fwd_md_carbon_unadj    DOUBLE PRECISION,
fwd_md_carbon_adj      DOUBLE PRECISION,
fwd_lg_tl_cond         DECIMAL(13,10),
fwd_lg_tl_unadj        DECIMAL(13,10),
fwd_lg_tl_adj          DECIMAL(13,10),
fwd_lg_cnt_cond        DOUBLE PRECISION,
fwd_lg_volcf_cond      DOUBLE PRECISION,
fwd_lg_volcf_unadj     DOUBLE PRECISION,
fwd_lg_volcf_adj       DOUBLE PRECISION,
fwd_lg_drybio_cond     DOUBLE PRECISION,
fwd_lg_drybio_unadj    DOUBLE PRECISION,
fwd_lg_drybio_adj      DOUBLE PRECISION,
fwd_lg_carbon_cond     DOUBLE PRECISION,
fwd_lg_carbon_unadj    DOUBLE PRECISION,
fwd_lg_carbon_adj      DOUBLE PRECISION,
pile_sample_area_cond  DECIMAL(13,12),
pile_sample_area_unadj DECIMAL(13,12),
pile_sample_area_adj   DECIMAL(13,12),
pile_volcf_cond        DOUBLE PRECISION,
pile_volcf_unadj       DOUBLE PRECISION,
pile_volcf_adj         DOUBLE PRECISION,
pile_drybio_cond       DOUBLE PRECISION,
pile_drybio_unadj      DOUBLE PRECISION,
pile_drybio_adj        DOUBLE PRECISION,
pile_carbon_cond       DOUBLE PRECISION,
pile_carbon_unadj      DOUBLE PRECISION,
pile_carbon_adj        DOUBLE PRECISION,
fuel_depth             DOUBLE PRECISION,
fuel_biomass           DOUBLE PRECISION,
fuel_carbon            DOUBLE PRECISION,
duff_depth             DOUBLE PRECISION,
duff_biomass           DOUBLE PRECISION,
duff_carbon            DOUBLE PRECISION,
litter_depth           DOUBLE PRECISION,
litter_biomass         DOUBLE PRECISION,
litter_carbon          DOUBLE PRECISION,
duff_tc_cond           DECIMAL(14,12),
duff_tc_unadj          DECIMAL(14,12),
duff_tc_adj            DECIMAL(14,12),
avg_wood_density       DECIMAL(12,10),
created_date           TIMESTAMP(0) NOT NULL,
modified_date          TIMESTAMP(0),
cycle                  INTEGER NOT NULL,
subcycle               INTEGER NOT NULL,
unitcd                 INTEGER NOT NULL,
rscd                   INTEGER,
pile_tl_cond           DECIMAL(13,10),
pile_tl_unadj          DECIMAL(13,10),
pile_tl_adj            DECIMAL(13,10),
condprop_pile          DECIMAL(13,12)
);
create index CDC_CND_FK_I on FS_FIADB.COND_DWM_CALC (CND_CN);
create index CDC_PSM_FK_I on FS_FIADB.COND_DWM_CALC (STRATUM_CN);
create index CDC_PLT_FK_I on FS_FIADB.COND_DWM_CALC (PLT_CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_PK primary key (CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_UK unique (PLT_CN, CONDID, EVALID, RSCD);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_UK2 unique (STATECD, COUNTYCD, PLOT, INVYR, CONDID, EVALID, RSCD);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_UK3 unique (STATECD, CYCLE, SUBCYCLE, COUNTYCD, PLOT, CONDID, EVALID, RSCD);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_CND_FK foreign key (CND_CN) references FS_FIADB.COND (CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_PSM_FK foreign key (STRATUM_CN) references FS_FIADB.POP_STRATUM (CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);