CREATE TABLE fs_fiadb.subp_soil_sample_loc
(
cn                     VARCHAR(34) NOT NULL,
plt_cn                 VARCHAR(34) NOT NULL,
statecd                INTEGER NOT NULL,
countycd               INTEGER NOT NULL,
plot                   INTEGER NOT NULL,
inv_vst_nbr            INTEGER NOT NULL,
invyr                  INTEGER NOT NULL,
cycle                  INTEGER NOT NULL,
subcycle               INTEGER NOT NULL,
unitcd                 INTEGER NOT NULL,
subp                   INTEGER NOT NULL,
vstnbr                 INTEGER,
condid                 INTEGER NOT NULL,
soils_sample_method_cd INTEGER NOT NULL,
soils_sample_status_cd INTEGER NOT NULL,
core_size              DECIMAL(4,3),
core_length            DECIMAL(3,1),
core_bottom_cd         INTEGER,
hole_depth             DECIMAL(3,1),
restriction_depth_cd_1 INTEGER,
restriction_depth_cd_2 INTEGER,
restriction_depth_cd_3 INTEGER,
restriction_depth_cd_4 INTEGER,
restriction_depth_1    DECIMAL(3,1),
restriction_depth_2    DECIMAL(3,1),
restriction_depth_3    DECIMAL(3,1),
restriction_depth_4    DECIMAL(3,1),
c_tot_3in_mg_ac        DECIMAL(10,6),
n_tot_3in_mg_ac        DECIMAL(10,6),
used_in_estimation_cd  INTEGER,
created_date           TIMESTAMP(0),
modified_date          TIMESTAMP(0)
);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LOC add constraint SSSL_PK primary key (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LOC add constraint SSSL_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);