CREATE TABLE fs_fiadb.tree_grm_component
(
tre_cn                       VARCHAR(34) NOT NULL,
prev_tre_cn                  VARCHAR(34),
plt_cn                       VARCHAR(34) NOT NULL,
statecd                      DOUBLE PRECISION NOT NULL,
dia_begin                    DECIMAL(5,2),
dia_midpt                    DECIMAL(5,2),
dia_end                      DECIMAL(5,2),
ann_dia_growth               DECIMAL(5,2),
ann_ht_growth                DECIMAL(5,2),
subptyp_begin                INTEGER,
subptyp_midpt                INTEGER,
subptyp_end                  INTEGER,
micr_component_al_forest     VARCHAR(15),
micr_subptyp_grm_al_forest   INTEGER,
micr_tpagrow_unadj_al_forest DECIMAL(11,6),
micr_tparemv_unadj_al_forest DECIMAL(11,6),
micr_tpamort_unadj_al_forest DECIMAL(11,6),
subp_component_al_forest     VARCHAR(15),
subp_subptyp_grm_al_forest   INTEGER,
subp_tpagrow_unadj_al_forest DECIMAL(11,6),
subp_tparemv_unadj_al_forest DECIMAL(11,6),
subp_tpamort_unadj_al_forest DECIMAL(11,6),
subp_component_gs_forest     VARCHAR(15),
subp_subptyp_grm_gs_forest   INTEGER,
subp_tpagrow_unadj_gs_forest DECIMAL(11,6),
subp_tparemv_unadj_gs_forest DECIMAL(11,6),
subp_tpamort_unadj_gs_forest DECIMAL(11,6),
subp_component_sl_forest     VARCHAR(15),
subp_subptyp_grm_sl_forest   INTEGER,
subp_tpagrow_unadj_sl_forest DECIMAL(11,6),
subp_tparemv_unadj_sl_forest DECIMAL(11,6),
subp_tpamort_unadj_sl_forest DECIMAL(11,6),
micr_component_al_timber     VARCHAR(15),
micr_subptyp_grm_al_timber   INTEGER,
micr_tpagrow_unadj_al_timber DECIMAL(11,6),
micr_tparemv_unadj_al_timber DECIMAL(11,6),
micr_tpamort_unadj_al_timber DECIMAL(11,6),
subp_component_al_timber     VARCHAR(15),
subp_subptyp_grm_al_timber   INTEGER,
subp_tpagrow_unadj_al_timber DECIMAL(11,6),
subp_tparemv_unadj_al_timber DECIMAL(11,6),
subp_tpamort_unadj_al_timber DECIMAL(11,6),
subp_component_gs_timber     VARCHAR(15),
subp_subptyp_grm_gs_timber   INTEGER,
subp_tpagrow_unadj_gs_timber DECIMAL(11,6),
subp_tparemv_unadj_gs_timber DECIMAL(11,6),
subp_tpamort_unadj_gs_timber DECIMAL(11,6),
subp_component_sl_timber     VARCHAR(15),
subp_subptyp_grm_sl_timber   INTEGER,
subp_tpagrow_unadj_sl_timber DECIMAL(11,6),
subp_tparemv_unadj_sl_timber DECIMAL(11,6),
subp_tpamort_unadj_sl_timber DECIMAL(11,6),
growtsal_forest              DECIMAL(13,6),
growcfal_forest              DECIMAL(13,6),
growcfgs_forest              DECIMAL(13,6),
growbfsl_forest              DECIMAL(13,6),
remvtsal_forest              DECIMAL(13,6),
remvcfal_forest              DECIMAL(13,6),
remvcfgs_forest              DECIMAL(13,6),
remvbfsl_forest              DECIMAL(13,6),
morttsal_forest              DECIMAL(13,6),
mortcfal_forest              DECIMAL(13,6),
mortcfgs_forest              DECIMAL(13,6),
mortbfsl_forest              DECIMAL(13,6),
growtsal_timber              DECIMAL(13,6),
growcfal_timber              DECIMAL(13,6),
growcfgs_timber              DECIMAL(13,6),
growbfsl_timber              DECIMAL(13,6),
remvtsal_timber              DECIMAL(13,6),
remvcfal_timber              DECIMAL(13,6),
remvcfgs_timber              DECIMAL(13,6),
remvbfsl_timber              DECIMAL(13,6),
morttsal_timber              DECIMAL(13,6),
mortcfal_timber              DECIMAL(13,6),
mortcfgs_timber              DECIMAL(13,6),
mortbfsl_timber              DECIMAL(13,6),
created_date                 TIMESTAMP(0),
modified_date                TIMESTAMP(0)
);
create index TRE_GRM_CMP_IND1 on FS_FIADB.TREE_GRM_COMPONENT (PLT_CN);
create index TRE_GRM_CMP_IND2 on FS_FIADB.TREE_GRM_COMPONENT (PREV_TRE_CN);
create index TRE_GRM_CMP_IND3 on FS_FIADB.TREE_GRM_COMPONENT (STATECD);
alter table FS_FIADB.TREE_GRM_COMPONENT add constraint TRE_GRM_CMP_PK primary key (TRE_CN);
alter table FS_FIADB.TREE_GRM_COMPONENT add constraint TRE_GRM_CMP_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);