create table fs_fiadb.REF_SIEQN
(
 CN                   VARCHAR(34) not null,
 SIEQN_REF_CD         VARCHAR(6),
 SIEQN_REF_NOTES      VARCHAR(1000),
 SIEQN_LOC_DESC_FSVEG VARCHAR(500),
 SIEQN_AGE_BASIS      VARCHAR(10),
 CREATED_BY           VARCHAR(30),
 CREATED_DATE         TIMESTAMP(0),
 CREATED_IN_INSTANCE  VARCHAR(6),
 MODIFIED_BY          VARCHAR(30),
 MODIFIED_DATE        TIMESTAMP(0),
 MODIFIED_IN_INSTANCE VARCHAR(6)
);