alter table FS_FIADB.REF_SIEQN add constraint REF_SIEQN_PK primary key (CN);
alter table FS_FIADB.REF_SIEQN add constraint REF_SIEQN_UK unique (SIEQN_REF_CD);
create index RPD_SCI_NAME_I on FS_FIADB.REF_PLANT_DICTIONARY (SCIENTIFIC_NAME);
create index RPD_SYMBOL_I on FS_FIADB.REF_PLANT_DICTIONARY (SYMBOL);
create index RPD_COMMON_NAME_I on FS_FIADB.REF_PLANT_DICTIONARY (COMMON_NAME);
alter table FS_FIADB.REF_PLANT_DICTIONARY add constraint RPD_PK primary key (CN);
alter table FS_FIADB.REF_PLANT_DICTIONARY add constraint RPD_UK unique (SYMBOL_TYPE, SYMBOL, NEW_SYMBOL);
alter table FS_FIADB.REF_FVS_VAR_NAME add constraint RFVN_PK primary key (CN);
alter table FS_FIADB.REF_FVS_LOC_NAME add constraint RFLN_PK primary key (FVS_LOC_CD);
alter table FS_FIADB.REF_DAMAGE_AGENT_GROUP add constraint DAG_PK primary key (CODE);
alter table FS_FIADB.REF_DAMAGE_AGENT add constraint DA_PK primary key (CODE);
alter table FS_FIADB.REF_DAMAGE_AGENT add constraint DA_DAG_FK foreign key (DAG_CODE) references FS_FIADB.REF_DAMAGE_AGENT_GROUP (CODE);
alter table FS_FIADB.REF_OWNGRPCD add constraint REF_OWNGRPCD_PK primary key (OWNGRPCD);
alter table FS_FIADB.REF_DIFFERENCE_TEST_PER_ACRE add constraint DTPA_PK primary key (CN);
alter table FS_FIADB.REF_DIFFERENCE_TEST_TOTALS add constraint DTT_PK primary key (CN);
alter table FS_FIADB.REF_GRM_TYPE add constraint RGT_PK primary key (CN);
alter table FS_FIADB.REF_GRM_TYPE add constraint RGT_UK unique (RSCD, STATECD, START_INVYR);
create index SBPREGEN_PLT_FK_I on FS_FIADB.SUBPLOT_REGEN (PLT_CN);
create index SBPREGEN_SBP_FK_I on FS_FIADB.SUBPLOT_REGEN (SBP_CN);
alter table FS_FIADB.SUBPLOT_REGEN add constraint SBPREGEN_PK primary key (CN);
alter table FS_FIADB.SUBPLOT_REGEN add constraint SBPREGEN_UK unique (STATECD, COUNTYCD, PLOT, SUBP, INVYR);
alter table FS_FIADB.SUBPLOT_REGEN add constraint SBPREGEN_SBP_FK foreign key (SBP_CN) references FS_FIADB.SUBPLOT (CN);
alter table FS_FIADB.SUBPLOT_REGEN add constraint SBPREGEN_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index SDLREGEN_PLT_CND_I on FS_FIADB.SEEDLING_REGEN (PLT_CN, CND_CN);
create index SDLREGEN_PLT_FK_I on FS_FIADB.SEEDLING_REGEN (PLT_CN);
create index SDLREGEN_CND_FK_I on FS_FIADB.SEEDLING_REGEN (CND_CN);
create index SDLREGEN_SCD_FK_I on FS_FIADB.SEEDLING_REGEN (SCD_CN);
alter table FS_FIADB.SEEDLING_REGEN add constraint SDLREGEN_PK primary key (CN);
alter table FS_FIADB.SEEDLING_REGEN add constraint SDLREGEN_UK unique (STATECD, COUNTYCD, PLOT, SUBP, INVYR, SPCD, CONDID, SEEDLING_SOURCE_CD, LENGTH_CLASS_CD);
alter table FS_FIADB.SEEDLING_REGEN add constraint SDLREGEN_SCD_FK foreign key (SCD_CN) references FS_FIADB.SUBP_COND (CN);
alter table FS_FIADB.SEEDLING_REGEN add constraint SDLREGEN_CND_FK foreign key (CND_CN) references FS_FIADB.COND (CN);
alter table FS_FIADB.SEEDLING_REGEN add constraint SDLREGEN_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index PLTREGEN_PLT_FK_I on FS_FIADB.PLOT_REGEN (PLT_CN);
alter table FS_FIADB.PLOT_REGEN add constraint PLTREGEN_PK primary key (CN);
alter table FS_FIADB.PLOT_REGEN add constraint PLTREGEN_UK1 unique (STATECD, COUNTYCD, PLOT, INVYR);
alter table FS_FIADB.PLOT_REGEN add constraint PLTREGEN_UK2 unique (STATECD, COUNTYCD, PLOT, CYCLE, SUBCYCLE);
alter table FS_FIADB.PLOT_REGEN add constraint PLTREGEN_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.REF_FOREST_TYPE_GROUP add constraint FTGP_PK primary key (VALUE);

create index PLOTGEOM_IDX on FS_FIADB.PLOTGEOM (STATECD, INVYR, UNITCD, COUNTYCD, PLOT);
alter table FS_FIADB.PLOTGEOM add constraint PLOTGEOM_PK primary key (CN);
alter table FS_FIADB.PLOTGEOM add constraint PLOTGEOM_PLT_FK foreign key (CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.REF_POP_EVAL_TYP_DESCR add constraint PED_PK primary key (CN);
alter table FS_FIADB.REF_POP_EVAL_TYP_DESCR add constraint PED_UK unique (EVAL_TYP);
create index PSM_PEU_FK_I on FS_FIADB.POP_STRATUM (ESTN_UNIT_CN);
alter table FS_FIADB.POP_STRATUM add constraint PSM_PK primary key (CN);
alter table FS_FIADB.POP_STRATUM add constraint PSM_UK unique (RSCD, EVALID, ESTN_UNIT, STRATUMCD);
alter table FS_FIADB.POP_STRATUM add constraint PSM_PEU_FK foreign key (ESTN_UNIT_CN) references FS_FIADB.POP_ESTN_UNIT (CN);
create index PET_PEG_FK_I on FS_FIADB.POP_EVAL_TYP (EVAL_GRP_CN);
create index PET_PEV_FK_I on FS_FIADB.POP_EVAL_TYP (EVAL_CN);
alter table FS_FIADB.POP_EVAL_TYP add constraint PET_PK primary key (CN);
alter table FS_FIADB.POP_EVAL_TYP add constraint PET_UK1 unique (EVAL_GRP_CN, EVAL_CN, EVAL_TYP);
alter table FS_FIADB.POP_EVAL_TYP add constraint PET_UK2 unique (EVAL_GRP_CN, EVAL_TYP);
alter table FS_FIADB.POP_EVAL_TYP add constraint PET_PEV_FK foreign key (EVAL_CN) references FS_FIADB.POP_EVAL (CN);
alter table FS_FIADB.POP_EVAL_TYP add constraint PET_PED_FK foreign key (EVAL_TYP) references FS_FIADB.REF_POP_EVAL_TYP_DESCR (EVAL_TYP);
alter table FS_FIADB.POP_EVAL_TYP add constraint PET_PEG_FK foreign key (EVAL_GRP_CN) references FS_FIADB.POP_EVAL_GRP (CN);
create index PEG_EVAL_I on FS_FIADB.POP_EVAL_GRP (EVAL_GRP);
alter table FS_FIADB.POP_EVAL_GRP add constraint PEG_PK primary key (CN);
alter table FS_FIADB.POP_EVAL_GRP add constraint PEG_UK unique (RSCD, EVAL_GRP);
alter table FS_FIADB.REF_INVASIVE_SPECIES add constraint RIS_PK primary key (CN);
alter table FS_FIADB.REF_INVASIVE_SPECIES add constraint RIS_UK unique (STATECD, SYMBOL);
create index P2VSSP_PLT_FK_I on FS_FIADB.P2VEG_SUBPLOT_SPP (PLT_CN);
alter table FS_FIADB.P2VEG_SUBPLOT_SPP add constraint P2VSSP_PK primary key (CN);
alter table FS_FIADB.P2VEG_SUBPLOT_SPP add constraint P2VSSP_UK unique (PLT_CN, VEG_FLDSPCD, UNIQUE_SP_NBR, SUBP, CONDID);
alter table FS_FIADB.P2VEG_SUBPLOT_SPP add constraint P2VSSP_SCD_FK foreign key (CONDID, SUBP, PLT_CN) references FS_FIADB.SUBP_COND (CONDID, SUBP, PLT_CN);
alter table FS_FIADB.P2VEG_SUBPLOT_SPP add constraint P2VSSP_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index PEA_PEV_FK_I on FS_FIADB.POP_EVAL_ATTRIBUTE (EVAL_CN);
create index PEA_PAE_FK_I on FS_FIADB.POP_EVAL_ATTRIBUTE (ATTRIBUTE_NBR);
alter table FS_FIADB.POP_EVAL_ATTRIBUTE add constraint PEA_UK unique (EVAL_CN, ATTRIBUTE_NBR);
alter table FS_FIADB.POP_EVAL_ATTRIBUTE add constraint PEA_PEV_FK foreign key (EVAL_CN) references FS_FIADB.POP_EVAL (CN);
alter table FS_FIADB.REF_HABTYP_DESCRIPTION add constraint RHN_PK primary key (CN);
alter table FS_FIADB.REF_HABTYP_DESCRIPTION add constraint RHN_UK unique (HABTYPCD, PUB_CD);
alter table FS_FIADB.REF_HABTYP_DESCRIPTION add constraint RHN_RPN_FK foreign key (PUB_CD) references FS_FIADB.REF_HABTYP_PUBLICATION (PUB_CD);
create index VPS_NAT_I on FS_FIADB.VEG_PLOT_SPECIES (STATECD, INVYR, COUNTYCD, PLOT, VEG_FLDSPCD, UNIQUE_SP_NBR);
alter table FS_FIADB.VEG_PLOT_SPECIES add constraint VPS_PK primary key (CN);
alter table FS_FIADB.VEG_PLOT_SPECIES add constraint VPS_UK unique (PLT_CN, VVT_CN, VEG_FLDSPCD, UNIQUE_SP_NBR);
alter table FS_FIADB.VEG_PLOT_SPECIES add constraint VPS_UK2 unique (PLT_CN, VVT_CN, CN);
create index TRE_NAT_I on FS_FIADB.TREE (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, SUBP, TREE);
create index TRE_SPGRPCD on FS_FIADB.TREE (SPGRPCD);
create index TRE_PLT_CN_CONDID on FS_FIADB.TREE (PLT_CN, CONDID);
create index TRE_PLT_FK_I on FS_FIADB.TREE (PLT_CN);
create index TRE_SPCD on FS_FIADB.TREE (SPCD);
alter table FS_FIADB.TREE add constraint TRE_PK primary key (CN);
alter table FS_FIADB.TREE add constraint TRE_UK unique (PLT_CN, SUBP, TREE);
alter table FS_FIADB.TREE add constraint TRE_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index VSS_NAT_I on FS_FIADB.VEG_SUBPLOT_SPP (STATECD, INVYR, COUNTYCD, PLOT, SUBP, UNIQUE_SP_NBR, VEG_SPCD);
create index VSS_VPS_FK_I on FS_FIADB.VEG_SUBPLOT_SPP (PLT_CN, VVT_CN, VPS_CN);
create index VSS_VSB_FK_I on FS_FIADB.VEG_SUBPLOT_SPP (PLT_CN, VVT_CN, VSB_CN);
alter table FS_FIADB.VEG_SUBPLOT_SPP add constraint VSS_PK primary key (CN);
alter table FS_FIADB.VEG_SUBPLOT_SPP add constraint VSS_UK unique (PLT_CN, VVT_CN, VPS_CN, VSB_CN);
alter table FS_FIADB.VEG_SUBPLOT_SPP add constraint VSS_VPS_FK foreign key (VPS_CN, PLT_CN, VVT_CN) references FS_FIADB.VEG_PLOT_SPECIES (CN, PLT_CN, VVT_CN);
alter table FS_FIADB.VEG_SUBPLOT_SPP add constraint VSS_VSB_FK foreign key (PLT_CN, VVT_CN, VSB_CN) references FS_FIADB.VEG_SUBPLOT (PLT_CN, VVT_CN, CN);
create index SDL_NAT_I on FS_FIADB.SEEDLING (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, SUBP, CONDID, SPCD);
create index SDL_PLT_FK_I on FS_FIADB.SEEDLING (PLT_CN);
alter table FS_FIADB.SEEDLING add constraint SDL_PK primary key (CN);
alter table FS_FIADB.SEEDLING add constraint SDL_UK unique (PLT_CN, SUBP, CONDID, SPCD);
alter table FS_FIADB.SEEDLING add constraint SDL_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index VQT_NAT_I on FS_FIADB.VEG_QUADRAT (STATECD, INVYR, COUNTYCD, PLOT, SUBP, QUADRAT);
create index VQT_VSB_FK_I on FS_FIADB.VEG_QUADRAT (PLT_CN, VVT_CN, VSB_CN);
alter table FS_FIADB.VEG_QUADRAT add constraint VQT_PK primary key (CN);
alter table FS_FIADB.VEG_QUADRAT add constraint VQT_UK unique (PLT_CN, VVT_CN, VSB_CN, QUADRAT);
alter table FS_FIADB.VEG_QUADRAT add constraint VQT_UK2 unique (PLT_CN, VVT_CN, VSB_CN, CN);
alter table FS_FIADB.VEG_QUADRAT add constraint VQT_VSB_FK foreign key (VVT_CN, PLT_CN, VSB_CN) references FS_FIADB.VEG_SUBPLOT (VVT_CN, PLT_CN, CN);
alter table FS_FIADB.REF_LICHEN_SPECIES add constraint LNS_PK primary key (CN);
alter table FS_FIADB.REF_LICHEN_SPECIES add constraint LNS_UK unique (LICH_SPPCD, SPP_ACRONYM, GENUS, YEARSTART);
alter table FS_FIADB.REF_FOREST_TYPE add constraint RFT_PK primary key (VALUE);
create index NOP_CTY_FK_I on FS_FIADB.OZONE_PLOT (CTY_CN);
create index NOP_SRV_FK_I on FS_FIADB.OZONE_PLOT (SRV_CN);
alter table FS_FIADB.OZONE_PLOT add constraint NOP_PK primary key (CN);
alter table FS_FIADB.OZONE_PLOT add constraint NOP_UK unique (STATECD, INVYR, COUNTYCD, O3PLOT, FIELD_ID, SPLIT_PLOTID);
alter table FS_FIADB.OZONE_PLOT add constraint NOP_CTY_FK foreign key (CTY_CN) references FS_FIADB.COUNTY (CN);
alter table FS_FIADB.OZONE_PLOT add constraint NOP_SRV_FK foreign key (SRV_CN) references FS_FIADB.SURVEY (CN);
create index DMF_NAT_I on FS_FIADB.DWM_MICROPLOT_FUEL (STATECD, INVYR, COUNTYCD, PLOT, SUBP);
alter table FS_FIADB.DWM_MICROPLOT_FUEL add constraint DMF_PK primary key (CN);
alter table FS_FIADB.DWM_MICROPLOT_FUEL add constraint DMF_UK unique (PLT_CN, SUBP);
create index LCH_NAT_I on FS_FIADB.LICHEN_LAB (STATECD, INVYR, COUNTYCD, PLOT, LICH_SPPCD);
alter table FS_FIADB.LICHEN_LAB add constraint LCH_PK primary key (CN);
alter table FS_FIADB.LICHEN_LAB add constraint LCH_UK unique (PLT_CN, LICH_SPPCD);
alter table FS_FIADB.LICHEN_LAB add constraint LCH_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.REF_UNIT add constraint UNT_PK primary key (STATECD, VALUE);
create index RFTN_PK on FS_FIADB.REF_FOREST_TYPE_NIMAC (CODE);

create index GRND_CVR_PLT_FK_I on FS_FIADB.GRND_CVR (PLT_CN);
create index GRND_CVR_UK_I on FS_FIADB.GRND_CVR (PLT_CN, SUBP, TRANSECT, GRND_CVR_SEG, GRND_CVR_TYP);
alter table FS_FIADB.GRND_CVR add constraint GRND_CVR_PK primary key (CN);
alter table FS_FIADB.GRND_CVR add constraint GRND_CVR_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index WOODS_PLT_FK_I on FS_FIADB.TREE_WOODLAND_STEMS (PLT_CN);
alter table FS_FIADB.TREE_WOODLAND_STEMS add constraint WOODS_PK primary key (CN);
alter table FS_FIADB.TREE_WOODLAND_STEMS add constraint WOODS_UK2 unique (PLT_CN, SUBP, TREE, STEM_NBR);
alter table FS_FIADB.TREE_WOODLAND_STEMS add constraint WOODS_UK unique (TRE_CN, STEM_NBR);
alter table FS_FIADB.TREE_WOODLAND_STEMS add constraint WOODS_TRE_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);
alter table FS_FIADB.TREE_WOODLAND_STEMS add constraint WOODS_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index OVN_NAT_I on FS_FIADB.OZONE_VALIDATION (STATECD, INVYR, COUNTYCD, O3PLOT, FIELD_ID, SPLIT_PLOTID, BIOSPCD);
alter table FS_FIADB.OZONE_VALIDATION add constraint OVN_PK primary key (CN);
alter table FS_FIADB.OZONE_VALIDATION add constraint OVN_UK unique (PLT_CN, BIOSPCD);
create index SCD_NAT_I on FS_FIADB.SUBP_COND (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, SUBP, CONDID);
create index SCD_SBP_FK_I on FS_FIADB.SUBP_COND (PLT_CN, SUBP);
create index SCD_CND_FK_I on FS_FIADB.SUBP_COND (PLT_CN, CONDID);
create index SCD_PLT_FK_I on FS_FIADB.SUBP_COND (PLT_CN);
alter table FS_FIADB.SUBP_COND add constraint SCD_PK primary key (CN);
alter table FS_FIADB.SUBP_COND add constraint SCD_UK unique (PLT_CN, SUBP, CONDID);
alter table FS_FIADB.SUBP_COND add constraint SCD_SBP_FK foreign key (PLT_CN, SUBP) references FS_FIADB.SUBPLOT (PLT_CN, SUBP);
alter table FS_FIADB.SUBP_COND add constraint SCD_CND_FK foreign key (PLT_CN, CONDID) references FS_FIADB.COND (PLT_CN, CONDID);
alter table FS_FIADB.SUBP_COND add constraint SCD_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index SSL_NAT_I on FS_FIADB.SOILS_SAMPLE_LOC (STATECD, INVYR, COUNTYCD, PLOT, SMPLNNBR);
alter table FS_FIADB.SOILS_SAMPLE_LOC add constraint SSL_PK primary key (CN);
alter table FS_FIADB.SOILS_SAMPLE_LOC add constraint SSL_UK unique (PLT_CN, SMPLNNBR);
alter table FS_FIADB.SOILS_SAMPLE_LOC add constraint SSL_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index VSB_NAT_I on FS_FIADB.VEG_SUBPLOT (STATECD, INVYR, COUNTYCD, PLOT, SUBP);
alter table FS_FIADB.VEG_SUBPLOT add constraint VSB_PK primary key (CN);
alter table FS_FIADB.VEG_SUBPLOT add constraint VSB_UK2 unique (PLT_CN, VVT_CN, CN);
alter table FS_FIADB.VEG_SUBPLOT add constraint VSB_UK unique (PLT_CN, VVT_CN, SUBP);
create index CND_NAT_I on FS_FIADB.COND (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, CONDID);
create index CND_PLT_FK_I on FS_FIADB.COND (PLT_CN);
alter table FS_FIADB.COND add constraint CND_PK primary key (CN);
alter table FS_FIADB.COND add constraint CND_UK unique (PLT_CN, CONDID);
alter table FS_FIADB.COND add constraint CND_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index DVT_NAT_I on FS_FIADB.DWM_VISIT (STATECD, INVYR, COUNTYCD, PLOT);
alter table FS_FIADB.DWM_VISIT add constraint DVT_PK primary key (CN);
alter table FS_FIADB.DWM_VISIT add constraint DVT_UK unique (PLT_CN);
alter table FS_FIADB.DWM_VISIT add constraint DVT_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.REF_CITATION add constraint CIT_PK primary key (CITATION_NBR, CITATION_NBR, CITATION_NBR, CITATION_NBR, CITATION_NBR, CITATION_NBR, CITATION_NBR, CITATION_NBR);
create index PLT_SRV_FK_I on FS_FIADB.PLOT (SRV_CN);
create index PLT_CTY_FK_I on FS_FIADB.PLOT (CTY_CN);
alter table FS_FIADB.PLOT add constraint PLT_PK primary key (CN);
alter table FS_FIADB.PLOT add constraint PLT_UK unique (STATECD, INVYR, UNITCD, COUNTYCD, PLOT);
alter table FS_FIADB.PLOT add constraint PLT_CTY_FK foreign key (CTY_CN) references FS_FIADB.COUNTY (CN);
alter table FS_FIADB.PLOT add constraint PLT_SRV_FK foreign key (SRV_CN) references FS_FIADB.SURVEY (CN);
create index PPSA_PSM_FK_I on FS_FIADB.POP_PLOT_STRATUM_ASSGN (STRATUM_CN);
create index PPSA_PLT_FK_I on FS_FIADB.POP_PLOT_STRATUM_ASSGN (PLT_CN);
alter table FS_FIADB.POP_PLOT_STRATUM_ASSGN add constraint PPSA_PK primary key (CN);
alter table FS_FIADB.POP_PLOT_STRATUM_ASSGN add constraint PPSA_UK unique (RSCD, EVALID, STATECD, COUNTYCD, PLOT);
alter table FS_FIADB.POP_PLOT_STRATUM_ASSGN add constraint PPSA_PSM_FK foreign key (STRATUM_CN) references FS_FIADB.POP_STRATUM (CN);
alter table FS_FIADB.POP_PLOT_STRATUM_ASSGN add constraint PPSA_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index OVT_NAT_I on FS_FIADB.OZONE_VISIT (STATECD, INVYR, COUNTYCD, O3PLOT, FIELD_ID, SPLIT_PLOTID);
alter table FS_FIADB.OZONE_VISIT add constraint OVT_PK primary key (CN);
alter table FS_FIADB.OZONE_VISIT add constraint OVT_UK unique (PLT_CN);
alter table FS_FIADB.OZONE_VISIT add constraint OVT_NOP_FK foreign key (PLT_CN) references FS_FIADB.OZONE_PLOT (CN);
alter table FS_FIADB.OZONE_PLOT_SUMMARY add constraint OPS_PK primary key (CN);
alter table FS_FIADB.OZONE_PLOT_SUMMARY add constraint OPS_UK unique (STATECD, INVYR, COUNTYCD, O3PLOT, FIELD_ID, SPLIT_PLOTID);
alter table FS_FIADB.REF_FIADB_VERSION add constraint RFN_PK primary key (VERSION);
create index P2VSS_PLT_CN_CONDID on FS_FIADB.P2VEG_SUBP_STRUCTURE (PLT_CN, CONDID);
create index P2VSS_PLT_FK_I on FS_FIADB.P2VEG_SUBP_STRUCTURE (PLT_CN);
alter table FS_FIADB.P2VEG_SUBP_STRUCTURE add constraint P2VSS_PK primary key (CN);
alter table FS_FIADB.P2VEG_SUBP_STRUCTURE add constraint P2VSS_UK unique (PLT_CN, SUBP, CONDID, GROWTH_HABIT_CD, LAYER);
alter table FS_FIADB.P2VEG_SUBP_STRUCTURE add constraint P2VSS_UK2 unique (STATECD, COUNTYCD, PLOT, INVYR, SUBP, CONDID, GROWTH_HABIT_CD, LAYER);
alter table FS_FIADB.P2VEG_SUBP_STRUCTURE add constraint P2VSS_UK3 unique (STATECD, CYCLE, SUBCYCLE, COUNTYCD, PLOT, SUBP, CONDID, GROWTH_HABIT_CD, LAYER);
alter table FS_FIADB.P2VEG_SUBP_STRUCTURE add constraint P2VSS_SCD_FK foreign key (SUBP, CONDID, PLT_CN) references FS_FIADB.SUBP_COND (SUBP, CONDID, PLT_CN);
alter table FS_FIADB.P2VEG_SUBP_STRUCTURE add constraint P2VSS_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index PEV_PEG_FK_I on FS_FIADB.POP_EVAL (EVAL_GRP_CN);
alter table FS_FIADB.POP_EVAL add constraint PEV_PK primary key (CN);
alter table FS_FIADB.POP_EVAL add constraint PEV_UK unique (RSCD, EVALID);
alter table FS_FIADB.POP_EVAL add constraint PEV_PEG_FK foreign key (EVAL_GRP_CN) references FS_FIADB.POP_EVAL_GRP (CN);
alter table FS_FIADB.BEGINEND add constraint BE_UK unique (ONEORTWO);
create index TGE_TRE_FK_I on FS_FIADB.TREE_GRM_ESTN (TRE_CN);
create index TGE_PLT_FK_I on FS_FIADB.TREE_GRM_ESTN (PLT_CN);
create index TGE_STATECD_INVYR_I on FS_FIADB.TREE_GRM_ESTN (STATECD, INVYR);
alter table FS_FIADB.TREE_GRM_ESTN add constraint TGE_PK primary key (CN);
alter table FS_FIADB.TREE_GRM_ESTN add constraint TGE_UK unique (TRE_CN, LAND_BASIS, ESTIMATE, ESTN_TYPE, ESTN_UNITS);
alter table FS_FIADB.TREE_GRM_ESTN add constraint TGE_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.TREE_GRM_ESTN add constraint TGE_TRE_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);
create index ISS_SCD_FK_I on FS_FIADB.INVASIVE_SUBPLOT_SPP (PLT_CN, SUBP, CONDID);
create index ISS_PLT_FK_I on FS_FIADB.INVASIVE_SUBPLOT_SPP (PLT_CN);
alter table FS_FIADB.INVASIVE_SUBPLOT_SPP add constraint ISS_PK primary key (CN);
alter table FS_FIADB.INVASIVE_SUBPLOT_SPP add constraint ISS_UK unique (PLT_CN, VEG_FLDSPCD, UNIQUE_SP_NBR, SUBP, CONDID);
alter table FS_FIADB.INVASIVE_SUBPLOT_SPP add constraint ISS_SCD_FK foreign key (PLT_CN, SUBP, CONDID) references FS_FIADB.SUBP_COND (PLT_CN, SUBP, CONDID);
alter table FS_FIADB.INVASIVE_SUBPLOT_SPP add constraint ISS_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index CDC_CND_FK_I on FS_FIADB.COND_DWM_CALC (CND_CN);
create index CDC_PSM_FK_I on FS_FIADB.COND_DWM_CALC (STRATUM_CN);
create index CDC_PLT_FK_I on FS_FIADB.COND_DWM_CALC (PLT_CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_PK primary key (CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_UK unique (PLT_CN, CONDID, EVALID, RSCD);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_UK2 unique (STATECD, COUNTYCD, PLOT, INVYR, CONDID, EVALID, RSCD);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_UK3 unique (STATECD, CYCLE, SUBCYCLE, COUNTYCD, PLOT, CONDID, EVALID, RSCD);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_CND_FK foreign key (CND_CN) references FS_FIADB.COND (CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_PSM_FK foreign key (STRATUM_CN) references FS_FIADB.POP_STRATUM (CN);
alter table FS_FIADB.COND_DWM_CALC add constraint CDC_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index DTS_NAT_I on FS_FIADB.DWM_TRANSECT_SEGMENT (STATECD, INVYR, COUNTYCD, PLOT, SUBP, TRANSECT, SEGMNT);
alter table FS_FIADB.DWM_TRANSECT_SEGMENT add constraint DTS_PK primary key (CN);
alter table FS_FIADB.DWM_TRANSECT_SEGMENT add constraint DTS_UK unique (PLT_CN, SUBP, TRANSECT, SEGMNT);
create index DDL_NAT_I on FS_FIADB.DWM_DUFF_LITTER_FUEL (STATECD, INVYR, COUNTYCD, PLOT, TRANSECT, SUBP, SMPLOCCD);
alter table FS_FIADB.DWM_DUFF_LITTER_FUEL add constraint DDL_PK primary key (CN);
alter table FS_FIADB.DWM_DUFF_LITTER_FUEL add constraint DDL_UK unique (PLT_CN, TRANSECT, SUBP, SMPLOCCD);
create index DCW_NAT_I on FS_FIADB.DWM_COARSE_WOODY_DEBRIS (STATECD, INVYR, COUNTYCD, PLOT, TRANSECT, SUBP, CWDID);
alter table FS_FIADB.DWM_COARSE_WOODY_DEBRIS add constraint DCW_PK primary key (CN);
alter table FS_FIADB.DWM_COARSE_WOODY_DEBRIS add constraint DCW_UK unique (PLT_CN, TRANSECT, SUBP, CWDID);
create index DRP_NAT_I on FS_FIADB.DWM_RESIDUAL_PILE (STATECD, INVYR, COUNTYCD, PLOT, SUBP, PILE);
alter table FS_FIADB.DWM_RESIDUAL_PILE add constraint DRP_PK primary key (CN);
alter table FS_FIADB.DWM_RESIDUAL_PILE add constraint DRP_UK unique (PLT_CN, SUBP, TRANSECT, PILE);
create index DFW_NAT_I on FS_FIADB.DWM_FINE_WOODY_DEBRIS (STATECD, INVYR, COUNTYCD, PLOT, TRANSECT, SUBP, CONDID);
alter table FS_FIADB.DWM_FINE_WOODY_DEBRIS add constraint DFW_PK primary key (CN);
alter table FS_FIADB.DWM_FINE_WOODY_DEBRIS add constraint DFW_UK unique (PLT_CN, TRANSECT, SUBP, CONDID);
alter table FS_FIADB.REF_RESEARCH_STATION add constraint RES_PK primary key (STATECD);
alter table FS_FIADB.EVALIDATOR_VARIABLE_LIBRARY add constraint EVL_PK primary key (LABEL_VAR);
alter table FS_FIADB.OZONE_BIOSITE_SUMMARY add constraint OBS_PK primary key (CN);
alter table FS_FIADB.OZONE_BIOSITE_SUMMARY add constraint OBS_UK unique (STATECD, INVYR, COUNTYCD, O3PLOT, FIELD_ID);
create index LPS_NAT_I on FS_FIADB.LICHEN_PLOT_SUMMARY (STATECD, INVYR, COUNTYCD, PLOT);
alter table FS_FIADB.LICHEN_PLOT_SUMMARY add constraint LPS_PK primary key (CN);
alter table FS_FIADB.LICHEN_PLOT_SUMMARY add constraint LPS_UK unique (PLT_CN);
alter table FS_FIADB.LICHEN_PLOT_SUMMARY add constraint LPS_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index VVT_NAT_I on FS_FIADB.VEG_VISIT (STATECD, INVYR, COUNTYCD, PLOT);
alter table FS_FIADB.VEG_VISIT add constraint VVT_PK primary key (CN);
alter table FS_FIADB.VEG_VISIT add constraint VVT_UK unique (PLT_CN);
alter table FS_FIADB.VEG_VISIT add constraint VVT_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index SEN_NAT_I on FS_FIADB.SOILS_EROSION (STATECD, INVYR, COUNTYCD, PLOT, SUBP);
alter table FS_FIADB.SOILS_EROSION add constraint SEN_PK primary key (CN);
alter table FS_FIADB.SOILS_EROSION add constraint SEN_UK unique (PLT_CN, SUBP);
alter table FS_FIADB.REF_LICHEN_SPP_COMMENTS add constraint LCM_PK primary key (CN);
alter table FS_FIADB.REF_LICHEN_SPP_COMMENTS add constraint LCM_UK unique (LICH_SPPCD, SPP_NAME, YEARSTART);
create index SLB_NAT_I on FS_FIADB.SOILS_LAB (STATECD, INVYR, COUNTYCD, PLOT, SMPLNNBR, LAYER_TYPE);
alter table FS_FIADB.SOILS_LAB add constraint SLB_PK primary key (CN);
alter table FS_FIADB.SOILS_LAB add constraint SLB_UK unique (PLT_CN, SMPLNNBR, LAYER_TYPE);
create index SVT_NAT_I on FS_FIADB.SOILS_VISIT (STATECD, INVYR, COUNTYCD, PLOT);
alter table FS_FIADB.SOILS_VISIT add constraint SVT_PK primary key (CN);
alter table FS_FIADB.SOILS_VISIT add constraint SVT_UK unique (PLT_CN);
alter table FS_FIADB.SOILS_VISIT add constraint SVT_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index SIT_NAT_I on FS_FIADB.SITETREE (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, CONDID, TREE);
create index SIT_PLT_FK_I on FS_FIADB.SITETREE (PLT_CN);
create index SIT_CND_FK_I on FS_FIADB.SITETREE (PLT_CN, CONDID);
alter table FS_FIADB.SITETREE add constraint SIT_PK primary key (CN);
alter table FS_FIADB.SITETREE add constraint SIT_UK unique (PLT_CN, CONDID, TREE);
alter table FS_FIADB.SITETREE add constraint SIT_CND_FK foreign key (CONDID, PLT_CN) references FS_FIADB.COND (CONDID, PLT_CN);
alter table FS_FIADB.SITETREE add constraint SIT_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.REF_STATE_ELEV add constraint RSE_PK primary key (STATECD);
alter table FS_FIADB.LICHEN_SPECIES_SUMMARY add constraint LSY_PK primary key (CN);
alter table FS_FIADB.LICHEN_SPECIES_SUMMARY add constraint LSY_UK unique (INVYR, LICHEN_REGION, LICH_SPPCD);
alter table FS_FIADB.COUNTY add constraint CTY_PK primary key (CN);
alter table FS_FIADB.COUNTY add constraint CTY_UK unique (STATECD, UNITCD, COUNTYCD);
alter table FS_FIADB.SURVEY add constraint SRV_PK primary key (CN);
alter table FS_FIADB.SURVEY add constraint SRV_UK unique (PRJ_CN, STATECD, INVYR, P3_OZONE_IND, CYCLE, SUBCYCLE);
alter table FS_FIADB.SURVEY add constraint SRV_PRJ_FK foreign key (PRJ_CN) references FS_FIADB.PROJECT (CN);
alter table FS_FIADB.REF_HABTYP_PUBLICATION add constraint RPN_PK primary key (CN);
alter table FS_FIADB.REF_HABTYP_PUBLICATION add constraint RPN_UK unique (PUB_CD);

create index CMX_PLT_FK_I on FS_FIADB.SUBP_COND_CHNG_MTRX (PREV_PLT_CN);
create index CMX_PLT_FK2_I on FS_FIADB.SUBP_COND_CHNG_MTRX (PLT_CN);
alter table FS_FIADB.SUBP_COND_CHNG_MTRX add constraint CMX_PK primary key (CN);
alter table FS_FIADB.SUBP_COND_CHNG_MTRX add constraint CMX_UK unique (PLT_CN, PREV_PLT_CN, SUBP, SUBPTYP, CONDID, PREVCOND);
alter table FS_FIADB.SUBP_COND_CHNG_MTRX add constraint CMX_PLT_FK foreign key (PREV_PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.SUBP_COND_CHNG_MTRX add constraint CMX_PLT_FK2 foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index SBP_PLT_FK_I on FS_FIADB.SUBPLOT (PLT_CN);
create index SBP_CND_FK3_I on FS_FIADB.SUBPLOT (PLT_CN, MACRCOND);
create index SBP_CND_FK2_I on FS_FIADB.SUBPLOT (PLT_CN, MICRCOND);
create index SBP_CND_FK_I on FS_FIADB.SUBPLOT (PLT_CN, SUBPCOND);
create index SBP_NAT_I on FS_FIADB.SUBPLOT (STATECD, INVYR, UNITCD, COUNTYCD, PLOT, SUBP);
alter table FS_FIADB.SUBPLOT add constraint SBP_PK primary key (CN);
alter table FS_FIADB.SUBPLOT add constraint SBP_UK unique (PLT_CN, SUBP);
alter table FS_FIADB.SUBPLOT add constraint SBP_CND_FK foreign key (PLT_CN, SUBPCOND) references FS_FIADB.COND (PLT_CN, CONDID);
alter table FS_FIADB.SUBPLOT add constraint SBP_CND_FK3 foreign key (PLT_CN, MACRCOND) references FS_FIADB.COND (PLT_CN, CONDID);
alter table FS_FIADB.SUBPLOT add constraint SBP_CND_FK2 foreign key (PLT_CN, MICRCOND) references FS_FIADB.COND (PLT_CN, CONDID);
alter table FS_FIADB.SUBPLOT add constraint SBP_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
create index LVT_NAT_I on FS_FIADB.LICHEN_VISIT (STATECD, INVYR, PLOT, COUNTYCD);
alter table FS_FIADB.LICHEN_VISIT add constraint LVT_PK primary key (CN);
alter table FS_FIADB.LICHEN_VISIT add constraint LVT_UK unique (PLT_CN);
alter table FS_FIADB.LICHEN_VISIT add constraint LVT_PLT_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.OZONE_SPECIES_SUMMARY add constraint OSY_PK primary key (CN);
alter table FS_FIADB.OZONE_SPECIES_SUMMARY add constraint OSY_UK unique (STATECD, INVYR, COUNTYCD, O3PLOT, BIOSPCD);
create index PEU_PEV_FK_I on FS_FIADB.POP_ESTN_UNIT (EVAL_CN);
alter table FS_FIADB.POP_ESTN_UNIT add constraint PEU_PK primary key (CN);
alter table FS_FIADB.POP_ESTN_UNIT add constraint PEU_UK unique (RSCD, EVALID, ESTN_UNIT);
alter table FS_FIADB.POP_ESTN_UNIT add constraint PEU_PEV_FK foreign key (EVAL_CN) references FS_FIADB.POP_EVAL (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_1_CODES add constraint RNVCSHS1_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_1_CODES add constraint RNVCSHS1_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_2_CODES add constraint RNVCSHS2_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_2_CODES add constraint RNVCSHS2_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_3_CODES add constraint RNVCSHS3_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_3_CODES add constraint RNVCSHS3_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_4_CODES add constraint RNVCSHS4_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_4_CODES add constraint RNVCSHS4_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_5_CODES add constraint RNVCSHS5_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_5_CODES add constraint RNVCSHS5_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_6_CODES add constraint RNVCSHS6_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_6_CODES add constraint RNVCSHS6_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_7_CODES add constraint RNVCSHS7_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_7_CODES add constraint RNVCSHS7_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.REF_NVCS_LEVEL_8_CODES add constraint RNVCSHS8_PK primary key (CN);
alter table FS_FIADB.REF_NVCS_LEVEL_8_CODES add constraint RNVCSHS8_UK unique (PRIMARY_CLASS, NVCS_CODE);
alter table FS_FIADB.PROJECT add constraint PRJ_PK primary key (CN);
alter table FS_FIADB.PROJECT add constraint PRJ_UK unique (RSCD, NAME);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LOC add constraint SSSL_PK primary key (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LOC add constraint SSSL_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LAYER add constraint SSSLYR_PK primary key (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LAYER add constraint SSSLYR_FK2 foreign key (SSSL_CN) references FS_FIADB.SUBP_SOIL_SAMPLE_LOC (CN);
alter table FS_FIADB.SUBP_SOIL_SAMPLE_LAYER add constraint SSSLYR_FK foreign key (PLT_CN) references FS_FIADB.PLOT (CN);
alter table FS_FIADB.REF_INTL_TO_DOYLE_FACTOR add constraint RIDF_PK primary key (DIA_2INCH_CLASS, SOFTWOOD);
create index TRE_GRM_BGN_IND1 on FS_FIADB.TREE_GRM_BEGIN (PLT_CN);
create index TRE_GRM_BGN_IND2 on FS_FIADB.TREE_GRM_BEGIN (PREV_TRE_CN);
create index TRE_GRM_BGN_IND3 on FS_FIADB.TREE_GRM_BEGIN (STATECD);
alter table FS_FIADB.TREE_GRM_BEGIN add constraint TRE_GRM_BGN_PK primary key (TRE_CN);
alter table FS_FIADB.TREE_GRM_BEGIN add constraint TRE_GRM_BGN_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);
create index TRE_GRM_CMP_IND1 on FS_FIADB.TREE_GRM_COMPONENT (PLT_CN);
create index TRE_GRM_CMP_IND2 on FS_FIADB.TREE_GRM_COMPONENT (PREV_TRE_CN);
create index TRE_GRM_CMP_IND3 on FS_FIADB.TREE_GRM_COMPONENT (STATECD);
alter table FS_FIADB.TREE_GRM_COMPONENT add constraint TRE_GRM_CMP_PK primary key (TRE_CN);
alter table FS_FIADB.TREE_GRM_COMPONENT add constraint TRE_GRM_CMP_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);
create index TRE_GRM_MIDPT_IND1 on FS_FIADB.TREE_GRM_MIDPT (PLT_CN);
create index TRE_GRM_MIDPT_IND2 on FS_FIADB.TREE_GRM_MIDPT (PREV_TRE_CN);
create index TRE_GRM_MIDPT_IND3 on FS_FIADB.TREE_GRM_MIDPT (STATECD);
alter table FS_FIADB.TREE_GRM_MIDPT add constraint TRE_GRM_MIDPT_PK primary key (TRE_CN);
alter table FS_FIADB.TREE_GRM_MIDPT add constraint TRE_GRM_MIDPT_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);
create index TRE_GRM_THRESH_IND1 on FS_FIADB.TREE_GRM_THRESHOLD (PLT_CN);
create index TRE_GRM_THRESH_IND2 on FS_FIADB.TREE_GRM_THRESHOLD (PREV_TRE_CN);
create index TRE_GRM_THRESH_IND3 on FS_FIADB.TREE_GRM_THRESHOLD (STATECD);
alter table FS_FIADB.TREE_GRM_THRESHOLD add constraint TRE_GRM_THRESH_PK primary key (TRE_CN, THRESHOLD_TYPE);
alter table FS_FIADB.TREE_GRM_THRESHOLD add constraint TRE_GRM_THRESH_FK foreign key (TRE_CN) references FS_FIADB.TREE (CN);


alter table FS_FIADB.REF_TREE_CARBON_RATIO_DEAD add constraint REFTCRD_PK primary key (CN);
alter table FS_FIADB.REF_TREE_CARBON_RATIO_DEAD add constraint REFTCRD_UK unique (SFTWD_HRDWD, DECAYCD);
alter table FS_FIADB.REF_TREE_DECAY_PROP add constraint REFTDP_PK primary key (CN);
alter table FS_FIADB.REF_TREE_DECAY_PROP add constraint REFTDP_UK unique (DECAYCD, SFTWD_HRDWD);
alter table FS_FIADB.REF_TREE_STND_DEAD_CR_PROP add constraint REFTSDCP_PK primary key (CN);
alter table FS_FIADB.REF_TREE_STND_DEAD_CR_PROP add constraint REFTSDCP_UK unique (ECOPROV, SFTWD_HRDWD);
alter table FS_FIADB.REF_GRND_LYR add constraint REFGLYR_PK primary key (CN);
alter table FS_FIADB.REF_GRND_LYR add constraint REFGLYR_UK unique (GRND_LYR_CONFIG, FUNCTIONAL_GROUP_CD);
create index RSG_SPGRPCD_I on FS_FIADB.REF_SPECIES_GROUP (SPGRPCD);
